let x : int option = Some 1
let x = (Some) 1
let x = Some @@ 1
(* let x = (Some..) 1 *)
let x = (None)
(* let x = (None..) *)
type t = Foo of int * float
let x : t = (Foo) (1,1.0)
let x : t = (Foo..) 1 1.0
let x : int -> float -> t = Foo[@curried] (* equivalent with (Foo..) *)
let x : (int * float) -> t = Foo
let x : (int * float) -> t = fun x -> Foo x
let x = (.contents)
let x = (#m)
